docs:
  - Cloud: mkdocs_Cloud.yml
  - Antwerpen/Linux: mkdocs_Antwerpen_Linux.yml
  - Antwerpen/MacOS: mkdocs_Antwerpen_MacOS.yml
  - Antwerpen/Windows: mkdocs_Antwerpen_Windows.yml
  - Gent/Linux: mkdocs_Gent_Linux.yml
  - Gent/MacOS: mkdocs_Gent_MacOS.yml
  - Gent/Windows: mkdocs_Gent_Windows.yml
os_picks:
  - Antwerpen: mkdocs_Antwerpen_OS_pick.yml
  - Gent: mkdocs_Gent_OS_pick.yml
#  - Brussel/Linux
#  - Brussel/MacOS
#  - Brussel/Windows
#  - Leuven/Linux
#  - Leuven/MacOS
#  - Leuven/Windows
